version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: >-
    cd ZKWeb

    dotnet restore
build:
  project: ZKWeb/ZKWeb.sln
  verbosity: minimal
after_build:
- cmd: >-
    dir

    cd ZKWeb.Console

    dotnet run -f net461

    dotnet run -f netcoreapp2.0
